/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedBusinessSettingsRouteImport } from './routes/_authenticated/business-settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedManageWorkerRouteImport } from './routes/_authenticated/manage-worker'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedRentalsRouteImport } from './routes/_authenticated/rentals'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedWorkerRouteImport } from './routes/_authenticated/worker'
import { Route as AuthenticatedWorkerLocationsRouteImport } from './routes/_authenticated/worker-locations'
import { Route as AuthLinkRouteImport } from './routes/auth.link'
import { Route as AuthGoogleRouteImport } from './routes/auth.google'
import { Route as ReceiptIdRouteImport } from './routes/receipt/$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedLabourIndexRouteImport } from './routes/_authenticated/labour/index'
import { Route as AuthenticatedLabourIdRouteImport } from './routes/_authenticated/labour/$id'
import { Route as AuthenticatedPlatformBusinessesRouteImport } from './routes/_authenticated/platform.businesses'
import { Route as AuthenticatedPlatformRequestsRouteImport } from './routes/_authenticated/platform.requests'
import { Route as AuthenticatedPlatformUsersRouteImport } from './routes/_authenticated/platform.users'
import { Route as AuthenticatedReceiptsIndexRouteImport } from './routes/_authenticated/receipts/index'
import { Route as AuthenticatedReceiptsIdRouteImport } from './routes/_authenticated/receipts/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBusinessSettingsRoute =
  AuthenticatedBusinessSettingsRouteImport.update({
    id: '/business-settings',
    path: '/business-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageWorkerRoute =
  AuthenticatedManageWorkerRouteImport.update({
    id: '/manage-worker',
    path: '/manage-worker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRentalsRoute = AuthenticatedRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerRoute = AuthenticatedWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerLocationsRoute =
  AuthenticatedWorkerLocationsRouteImport.update({
    id: '/worker-locations',
    path: '/worker-locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthLinkRoute = AuthLinkRouteImport.update({
  id: '/auth/link',
  path: '/auth/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLabourIndexRoute =
  AuthenticatedLabourIndexRouteImport.update({
    id: '/labour/',
    path: '/labour/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabourIdRoute = AuthenticatedLabourIdRouteImport.update({
  id: '/labour/$id',
  path: '/labour/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformBusinessesRoute =
  AuthenticatedPlatformBusinessesRouteImport.update({
    id: '/platform/businesses',
    path: '/platform/businesses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRequestsRoute =
  AuthenticatedPlatformRequestsRouteImport.update({
    id: '/platform/requests',
    path: '/platform/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformUsersRoute =
  AuthenticatedPlatformUsersRouteImport.update({
    id: '/platform/users',
    path: '/platform/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptsIndexRoute =
  AuthenticatedReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptsIdRoute = AuthenticatedReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/business-settings': typeof AuthenticatedBusinessSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/manage-worker': typeof AuthenticatedManageWorkerRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/rentals': typeof AuthenticatedRentalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/worker-locations': typeof AuthenticatedWorkerLocationsRoute
  '/auth/link': typeof AuthLinkRoute
  '/auth/google': typeof AuthGoogleRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/labour/$id': typeof AuthenticatedLabourIdRoute
  '/platform/businesses': typeof AuthenticatedPlatformBusinessesRoute
  '/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/labour/': typeof AuthenticatedLabourIndexRoute
  '/receipts/': typeof AuthenticatedReceiptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/business-settings': typeof AuthenticatedBusinessSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/manage-worker': typeof AuthenticatedManageWorkerRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/rentals': typeof AuthenticatedRentalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/worker-locations': typeof AuthenticatedWorkerLocationsRoute
  '/auth/link': typeof AuthLinkRoute
  '/auth/google': typeof AuthGoogleRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/labour/$id': typeof AuthenticatedLabourIdRoute
  '/platform/businesses': typeof AuthenticatedPlatformBusinessesRoute
  '/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/labour': typeof AuthenticatedLabourIndexRoute
  '/receipts': typeof AuthenticatedReceiptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/business-settings': typeof AuthenticatedBusinessSettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/manage-worker': typeof AuthenticatedManageWorkerRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/rentals': typeof AuthenticatedRentalsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/worker': typeof AuthenticatedWorkerRoute
  '/_authenticated/worker-locations': typeof AuthenticatedWorkerLocationsRoute
  '/auth/link': typeof AuthLinkRoute
  '/auth/google': typeof AuthGoogleRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/labour/$id': typeof AuthenticatedLabourIdRoute
  '/_authenticated/platform/businesses': typeof AuthenticatedPlatformBusinessesRoute
  '/_authenticated/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/_authenticated/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/_authenticated/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/_authenticated/labour/': typeof AuthenticatedLabourIndexRoute
  '/_authenticated/receipts/': typeof AuthenticatedReceiptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/business-settings'
    | '/dashboard'
    | '/diary'
    | '/feedback'
    | '/manage-worker'
    | '/reels'
    | '/rentals'
    | '/reports'
    | '/worker'
    | '/worker-locations'
    | '/auth/link'
    | '/auth/google'
    | '/receipt/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/labour/$id'
    | '/platform/businesses'
    | '/platform/requests'
    | '/platform/users'
    | '/receipts/$id'
    | '/labour/'
    | '/receipts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/business-settings'
    | '/dashboard'
    | '/diary'
    | '/feedback'
    | '/manage-worker'
    | '/reels'
    | '/rentals'
    | '/reports'
    | '/worker'
    | '/worker-locations'
    | '/auth/link'
    | '/auth/google'
    | '/receipt/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/labour/$id'
    | '/platform/businesses'
    | '/platform/requests'
    | '/platform/users'
    | '/receipts/$id'
    | '/labour'
    | '/receipts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/business-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/diary'
    | '/_authenticated/feedback'
    | '/_authenticated/manage-worker'
    | '/_authenticated/reels'
    | '/_authenticated/rentals'
    | '/_authenticated/reports'
    | '/_authenticated/worker'
    | '/_authenticated/worker-locations'
    | '/auth/link'
    | '/auth/google'
    | '/receipt/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/labour/$id'
    | '/_authenticated/platform/businesses'
    | '/_authenticated/platform/requests'
    | '/_authenticated/platform/users'
    | '/_authenticated/receipts/$id'
    | '/_authenticated/labour/'
    | '/_authenticated/receipts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthLinkRoute: typeof AuthLinkRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/business-settings': {
      id: '/_authenticated/business-settings'
      path: '/business-settings'
      fullPath: '/business-settings'
      preLoaderRoute: typeof AuthenticatedBusinessSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-worker': {
      id: '/_authenticated/manage-worker'
      path: '/manage-worker'
      fullPath: '/manage-worker'
      preLoaderRoute: typeof AuthenticatedManageWorkerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rentals': {
      id: '/_authenticated/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof AuthenticatedRentalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker': {
      id: '/_authenticated/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof AuthenticatedWorkerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker-locations': {
      id: '/_authenticated/worker-locations'
      path: '/worker-locations'
      fullPath: '/worker-locations'
      preLoaderRoute: typeof AuthenticatedWorkerLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/link': {
      id: '/auth/link'
      path: '/auth/link'
      fullPath: '/auth/link'
      preLoaderRoute: typeof AuthLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/labour/': {
      id: '/_authenticated/labour/'
      path: '/labour'
      fullPath: '/labour/'
      preLoaderRoute: typeof AuthenticatedLabourIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labour/$id': {
      id: '/_authenticated/labour/$id'
      path: '/labour/$id'
      fullPath: '/labour/$id'
      preLoaderRoute: typeof AuthenticatedLabourIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/businesses': {
      id: '/_authenticated/platform/businesses'
      path: '/platform/businesses'
      fullPath: '/platform/businesses'
      preLoaderRoute: typeof AuthenticatedPlatformBusinessesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/requests': {
      id: '/_authenticated/platform/requests'
      path: '/platform/requests'
      fullPath: '/platform/requests'
      preLoaderRoute: typeof AuthenticatedPlatformRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/users': {
      id: '/_authenticated/platform/users'
      path: '/platform/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof AuthenticatedPlatformUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts/': {
      id: '/_authenticated/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof AuthenticatedReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts/$id': {
      id: '/_authenticated/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof AuthenticatedReceiptsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBusinessSettingsRoute: typeof AuthenticatedBusinessSettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedManageWorkerRoute: typeof AuthenticatedManageWorkerRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedRentalsRoute: typeof AuthenticatedRentalsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedWorkerRoute: typeof AuthenticatedWorkerRoute
  AuthenticatedWorkerLocationsRoute: typeof AuthenticatedWorkerLocationsRoute
  AuthenticatedLabourIdRoute: typeof AuthenticatedLabourIdRoute
  AuthenticatedPlatformBusinessesRoute: typeof AuthenticatedPlatformBusinessesRoute
  AuthenticatedPlatformRequestsRoute: typeof AuthenticatedPlatformRequestsRoute
  AuthenticatedPlatformUsersRoute: typeof AuthenticatedPlatformUsersRoute
  AuthenticatedReceiptsIdRoute: typeof AuthenticatedReceiptsIdRoute
  AuthenticatedLabourIndexRoute: typeof AuthenticatedLabourIndexRoute
  AuthenticatedReceiptsIndexRoute: typeof AuthenticatedReceiptsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBusinessSettingsRoute: AuthenticatedBusinessSettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedManageWorkerRoute: AuthenticatedManageWorkerRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedRentalsRoute: AuthenticatedRentalsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedWorkerRoute: AuthenticatedWorkerRoute,
  AuthenticatedWorkerLocationsRoute: AuthenticatedWorkerLocationsRoute,
  AuthenticatedLabourIdRoute: AuthenticatedLabourIdRoute,
  AuthenticatedPlatformBusinessesRoute: AuthenticatedPlatformBusinessesRoute,
  AuthenticatedPlatformRequestsRoute: AuthenticatedPlatformRequestsRoute,
  AuthenticatedPlatformUsersRoute: AuthenticatedPlatformUsersRoute,
  AuthenticatedReceiptsIdRoute: AuthenticatedReceiptsIdRoute,
  AuthenticatedLabourIndexRoute: AuthenticatedLabourIndexRoute,
  AuthenticatedReceiptsIndexRoute: AuthenticatedReceiptsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthLinkRoute: AuthLinkRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}